export const mockData = [
    {
    "Symbol": "A",
    "Name": "Agilent Technologies Ink",
    "Last Sale": "$133.89",
    "Net Change": -3.28,
    "% Change": "-2.391%",
    "Market Cap": 40216018468,
    "Country": "United States",
    "IPO Year": 1999,
    "Volume": 3848506,
    "Sector": "Capital Goods",
    "Industry": "Electrical Products",
    "lastUpdated": null,
    "firstUpdated": null,
  },
  {
    "Symbol": "AA",
    "Name": "Alcoa Corporation",
    "Last Sale": "$90.66",
    "Net Change": 7.77,
    "% Change": "9.374%",
    "Market Cap": 16808638881,
    "Country": "",
    "IPO Year": 2016,
    "Volume": 19664587,
    "Sector": "Basic Industries",
    "Industry": "Metal Fabrications",
    "lastUpdated": null,
    "firstUpdated": null,
  },
  {
    "Symbol": "AAC",
    "Name": "Ares Acquisition Corporation",
    "Last Sale": "$9.77",
    "Net Change": 0.01,
    "% Change": "0.102%",
    "Market Cap": 1221250000,
    "Country": "",
    "IPO Year": 2021,
    "Volume": 74080,
    "Sector": "Finance",
    "Industry": "Business Services",
    "lastUpdated": null,
    "firstUpdated": null,
  },
  {
    "Symbol": "AACG",
    "Name": "ATA Creativity",
    "Last Sale": "$1.21",
    "Net Change": -0.03,
    "% Change": "-2.419%",
    "Market Cap": 37966073,
    "Country": "China",
    "IPO Year": "",
    "Volume": 34965,
    "Sector": "Miscellaneous",
    "Industry": "Service to the Health Industry",
    "lastUpdated": null,
    "firstUpdated": null,
  },
  {
    "Symbol": "AACI",
    "Name": "Armada Acquisition Corp",
    "Last Sale": "$9.81",
    "Net Change": 0,
    "% Change": "0.00%",
    "Market Cap": 203160195,
    "Country": "United States",
    "IPO Year": 2021,
    "Volume": 2,
    "Sector": "Health Care",
    "Industry": "Pharmaceutical",
    "lastUpdated": null,
    "firstUpdated": null,
  },
  {
    "Symbol": "AACIU",
    "Name": "Armada Acquisition Corp",
    "Last Sale": "$9.84",
    "Net Change": 0,
    "% Change": "0.00%",
    "Market Cap": 0,
    "Country": "United States",
    "IPO Year": 2021,
    "Volume": 1,
    "Sector": "Automobile",
    "Industry": "Manufacture",
    "lastUpdated": null,
    "firstUpdated": null,
  },
  {
    "Symbol": "AACIW",
    "Name": "Armada Acquisition Corp",
    "Last Sale": "$0.24",
    "Net Change": 0.002,
    "% Change": "0.84%",
    "Market Cap": 0,
    "Country": "United States",
    "IPO Year": 2021,
    "Volume": 4192,
    "Sector": "Consumer service",
    "Industry": "Real Estate",
    "lastUpdated": null,
    "firstUpdated": null,
  },
  {
    "Symbol": "AADI",
    "Name": "Aadi Bioscience Inc",
    "Last Sale": "$16.93",
    "Net Change": -0.05,
    "% Change": "-0.294%",
    "Market Cap": 353735911,
    "Country": "United States",
    "IPO Year": "",
    "Volume": 71825,
    "Sector": "Health Care",
    "Industry": "Biotechnology: Pharmaceutical Preparations",
    "lastUpdated": null,
    "firstUpdated": null,
  },
  {
    "Symbol": "AAIC",
    "Name": "Arlington Asset Investment",
    "Last Sale": "$3.50",
    "Net Change": 0.02,
    "% Change": "0.575%",
    "Market Cap": 110177967,
    "Country": "United States",
    "IPO Year": "",
    "Volume": 113264,
    "Sector": "Consumer Services",
    "Industry": "Real Estate Investment Trusts",
    "lastUpdated": null,
    "firstUpdated": null,
  },
  {
    "Symbol": "ACDI",
    "Name": "Ascendant Digital Acquisition Corps",
    "Last Sale": "$9.98",
    "Net Change": 0.03,
    "% Change": "0.302%",
    "Market Cap": 374250000,
    "Country": "",
    "IPO Year": 2021,
    "Volume": 200,
    "Sector": "Consumer Services",
    "Industry": "Digital",
    "lastUpdated": null,
    "firstUpdated": null,
  }
]